export default {
    GRID_SIZE : 21,
    SNAKE_SPEED : 5,
    SNAKE_INITIAL_POSITION : 11,
    SNAKE_EXPANSION_RATE : 1,
    FOOD_INITIAL_POSITION : 4,
    SCORE_INCREMENT : 50,
    SCORE_LIMIT : 6,
    SCROLL_ANIMATION_SPEED : 35
}